### ISSUE TITLE
Can I get srever-side api code?

### ISSUE THREAD

**Issue by lovebdsobuj** [Radio-UTD/Radio-UTD#9]

**Comment by rahatarmanahmed** [comment]
Sorry, didn't have access to the server side API. It was there while I was developing but I guess they must have removed it when they redesigned their website? It's a shame, I spent a lot of time on this but they never finished the API.

You'll have to contact whoever's in charge of the station website.

Out of curiosity, how'd you find this and what are you planning to do?

**Comment by rahatarmanahmed** [comment]
Also @crait could maybe get you in touch w/ the guy who wrote it.

**Comment by lovebdsobuj** [comment]
Wanted to use this source for a online radio station, that cause find server-side api code.

**Comment by rahatarmanahmed** [comment]
Ah, well the biggest thing you need to change is this, probably: https://github.com/Radio-UTD/Radio-UTD/blob/master/app/src/main/java/com/utd/radio/util/MetadataManager.java

You could either make a backend supply these w/ JSON or change it to fit your current API

**Comment by lovebdsobuj** [comment]
I don't have basic knowledge about this, but I should try...
